// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AttendanceRecord struct {
	ID               string
	SessionID        string
	StudentID        string
	AttendanceStatus string
	CheckInAt        pgtype.Timestamptz
	Notes            pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	LastModifiedAt   pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type AttendanceSession struct {
	ID             string
	ClubID         string
	SessionDate    pgtype.Date
	Status         string
	Notes          pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastModifiedAt pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type BeltRank struct {
	ID             string
	Name           string
	RankOrder      int32
	Description    pgtype.Text
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastModifiedAt pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type Club struct {
	ID             string
	Code           pgtype.Text
	Name           string
	Phone          pgtype.Text
	Email          pgtype.Text
	Address        pgtype.Text
	Notes          pgtype.Text
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastModifiedAt pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type ClubGroup struct {
	ID             string
	ClubID         string
	Name           string
	Description    pgtype.Text
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastModifiedAt pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type ClubSchedule struct {
	ID             string
	ClubID         string
	Weekday        string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastModifiedAt pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type Student struct {
	ID             string
	StudentCode    pgtype.Text
	FullName       string
	DateOfBirth    pgtype.Date
	Gender         pgtype.Text
	Phone          pgtype.Text
	Email          pgtype.Text
	Address        pgtype.Text
	ClubID         string
	GroupID        pgtype.Text
	BeltRankID     string
	JoinedAt       pgtype.Date
	Status         string
	Notes          pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastModifiedAt pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type StudentSchedule struct {
	ID             string
	StudentID      string
	Weekday        string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastModifiedAt pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type StudentScheduleProfile struct {
	ID             string
	StudentID      string
	Mode           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastModifiedAt pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}
