// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findActiveAttendanceRecordBySessionAndStudent = `-- name: FindActiveAttendanceRecordBySessionAndStudent :one
SELECT id, session_id, student_id, attendance_status, check_in_at, notes, created_at, updated_at, last_modified_at, deleted_at
FROM attendance_records
WHERE deleted_at IS NULL
	AND id <> $1
	AND session_id = $2
	AND student_id = $3
LIMIT 1
`

type FindActiveAttendanceRecordBySessionAndStudentParams struct {
	ID        string
	SessionID string
	StudentID string
}

func (q *Queries) FindActiveAttendanceRecordBySessionAndStudent(ctx context.Context, arg FindActiveAttendanceRecordBySessionAndStudentParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, findActiveAttendanceRecordBySessionAndStudent, arg.ID, arg.SessionID, arg.StudentID)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StudentID,
		&i.AttendanceStatus,
		&i.CheckInAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastModifiedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findActiveBeltRankByOrder = `-- name: FindActiveBeltRankByOrder :one
SELECT id, name, rank_order, description, is_active, created_at, updated_at, last_modified_at, deleted_at
FROM belt_ranks
WHERE deleted_at IS NULL
	AND id <> $1
	AND rank_order = $2
LIMIT 1
`

type FindActiveBeltRankByOrderParams struct {
	ID        string
	RankOrder int32
}

func (q *Queries) FindActiveBeltRankByOrder(ctx context.Context, arg FindActiveBeltRankByOrderParams) (BeltRank, error) {
	row := q.db.QueryRow(ctx, findActiveBeltRankByOrder, arg.ID, arg.RankOrder)
	var i BeltRank
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RankOrder,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastModifiedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findActiveClubByCode = `-- name: FindActiveClubByCode :one
SELECT id, code, name, phone, email, address, notes, is_active, created_at, updated_at, last_modified_at, deleted_at
FROM clubs
WHERE deleted_at IS NULL
	AND id <> $1
	AND code = $2
LIMIT 1
`

type FindActiveClubByCodeParams struct {
	ID   string
	Code pgtype.Text
}

func (q *Queries) FindActiveClubByCode(ctx context.Context, arg FindActiveClubByCodeParams) (Club, error) {
	row := q.db.QueryRow(ctx, findActiveClubByCode, arg.ID, arg.Code)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastModifiedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findActiveClubScheduleByWeekday = `-- name: FindActiveClubScheduleByWeekday :one
SELECT id, club_id, weekday, is_active, created_at, updated_at, last_modified_at, deleted_at
FROM club_schedules
WHERE deleted_at IS NULL
	AND id <> $1
	AND club_id = $2
	AND weekday = $3
LIMIT 1
`

type FindActiveClubScheduleByWeekdayParams struct {
	ID      string
	ClubID  string
	Weekday string
}

func (q *Queries) FindActiveClubScheduleByWeekday(ctx context.Context, arg FindActiveClubScheduleByWeekdayParams) (ClubSchedule, error) {
	row := q.db.QueryRow(ctx, findActiveClubScheduleByWeekday, arg.ID, arg.ClubID, arg.Weekday)
	var i ClubSchedule
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Weekday,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastModifiedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findActiveStudentByCode = `-- name: FindActiveStudentByCode :one
SELECT id, student_code, full_name, date_of_birth, gender, phone, email, address, club_id, group_id, belt_rank_id, joined_at, status, notes, created_at, updated_at, last_modified_at, deleted_at
FROM students
WHERE deleted_at IS NULL
	AND id <> $1
	AND student_code = $2
LIMIT 1
`

type FindActiveStudentByCodeParams struct {
	ID          string
	StudentCode pgtype.Text
}

func (q *Queries) FindActiveStudentByCode(ctx context.Context, arg FindActiveStudentByCodeParams) (Student, error) {
	row := q.db.QueryRow(ctx, findActiveStudentByCode, arg.ID, arg.StudentCode)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentCode,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.ClubID,
		&i.GroupID,
		&i.BeltRankID,
		&i.JoinedAt,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastModifiedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findActiveStudentScheduleByWeekday = `-- name: FindActiveStudentScheduleByWeekday :one
SELECT id, student_id, weekday, is_active, created_at, updated_at, last_modified_at, deleted_at
FROM student_schedules
WHERE deleted_at IS NULL
	AND id <> $1
	AND student_id = $2
	AND weekday = $3
LIMIT 1
`

type FindActiveStudentScheduleByWeekdayParams struct {
	ID        string
	StudentID string
	Weekday   string
}

func (q *Queries) FindActiveStudentScheduleByWeekday(ctx context.Context, arg FindActiveStudentScheduleByWeekdayParams) (StudentSchedule, error) {
	row := q.db.QueryRow(ctx, findActiveStudentScheduleByWeekday, arg.ID, arg.StudentID, arg.Weekday)
	var i StudentSchedule
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Weekday,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastModifiedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveAttendanceRecords = `-- name: ListActiveAttendanceRecords :many
SELECT id, session_id, student_id, attendance_status, check_in_at, notes, created_at, updated_at, last_modified_at, deleted_at
FROM attendance_records
WHERE deleted_at IS NULL
ORDER BY session_id ASC, student_id ASC
`

func (q *Queries) ListActiveAttendanceRecords(ctx context.Context) ([]AttendanceRecord, error) {
	rows, err := q.db.Query(ctx, listActiveAttendanceRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttendanceRecord
	for rows.Next() {
		var i AttendanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.StudentID,
			&i.AttendanceStatus,
			&i.CheckInAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAttendanceSessions = `-- name: ListActiveAttendanceSessions :many
SELECT id, club_id, session_date, status, notes, created_at, updated_at, last_modified_at, deleted_at
FROM attendance_sessions
WHERE deleted_at IS NULL
ORDER BY session_date DESC, updated_at DESC
`

func (q *Queries) ListActiveAttendanceSessions(ctx context.Context) ([]AttendanceSession, error) {
	rows, err := q.db.Query(ctx, listActiveAttendanceSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttendanceSession
	for rows.Next() {
		var i AttendanceSession
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.SessionDate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveBeltRanks = `-- name: ListActiveBeltRanks :many
SELECT id, name, rank_order, description, is_active, created_at, updated_at, last_modified_at, deleted_at
FROM belt_ranks
WHERE deleted_at IS NULL
ORDER BY rank_order ASC
`

func (q *Queries) ListActiveBeltRanks(ctx context.Context) ([]BeltRank, error) {
	rows, err := q.db.Query(ctx, listActiveBeltRanks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BeltRank
	for rows.Next() {
		var i BeltRank
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RankOrder,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveClubGroups = `-- name: ListActiveClubGroups :many
SELECT id, club_id, name, description, is_active, created_at, updated_at, last_modified_at, deleted_at
FROM club_groups
WHERE deleted_at IS NULL
ORDER BY club_id ASC, name ASC
`

func (q *Queries) ListActiveClubGroups(ctx context.Context) ([]ClubGroup, error) {
	rows, err := q.db.Query(ctx, listActiveClubGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClubGroup
	for rows.Next() {
		var i ClubGroup
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveClubScheduleWeekdays = `-- name: ListActiveClubScheduleWeekdays :many
SELECT weekday
FROM club_schedules
WHERE club_id = $1
	AND deleted_at IS NULL
	AND is_active = TRUE
ORDER BY weekday ASC
`

func (q *Queries) ListActiveClubScheduleWeekdays(ctx context.Context, clubID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveClubScheduleWeekdays, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var weekday string
		if err := rows.Scan(&weekday); err != nil {
			return nil, err
		}
		items = append(items, weekday)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveClubSchedules = `-- name: ListActiveClubSchedules :many
SELECT id, club_id, weekday, is_active, created_at, updated_at, last_modified_at, deleted_at
FROM club_schedules
WHERE deleted_at IS NULL
ORDER BY club_id ASC, weekday ASC
`

func (q *Queries) ListActiveClubSchedules(ctx context.Context) ([]ClubSchedule, error) {
	rows, err := q.db.Query(ctx, listActiveClubSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClubSchedule
	for rows.Next() {
		var i ClubSchedule
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Weekday,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveClubs = `-- name: ListActiveClubs :many
SELECT id, code, name, phone, email, address, notes, is_active, created_at, updated_at, last_modified_at, deleted_at
FROM clubs
WHERE deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListActiveClubs(ctx context.Context) ([]Club, error) {
	rows, err := q.db.Query(ctx, listActiveClubs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Club
	for rows.Next() {
		var i Club
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveStudentScheduleProfiles = `-- name: ListActiveStudentScheduleProfiles :many
SELECT id, student_id, mode, created_at, updated_at, last_modified_at, deleted_at
FROM student_schedule_profiles
WHERE deleted_at IS NULL
ORDER BY student_id ASC
`

func (q *Queries) ListActiveStudentScheduleProfiles(ctx context.Context) ([]StudentScheduleProfile, error) {
	rows, err := q.db.Query(ctx, listActiveStudentScheduleProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentScheduleProfile
	for rows.Next() {
		var i StudentScheduleProfile
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Mode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveStudentSchedules = `-- name: ListActiveStudentSchedules :many
SELECT id, student_id, weekday, is_active, created_at, updated_at, last_modified_at, deleted_at
FROM student_schedules
WHERE deleted_at IS NULL
ORDER BY student_id ASC, weekday ASC
`

func (q *Queries) ListActiveStudentSchedules(ctx context.Context) ([]StudentSchedule, error) {
	rows, err := q.db.Query(ctx, listActiveStudentSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentSchedule
	for rows.Next() {
		var i StudentSchedule
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Weekday,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveStudents = `-- name: ListActiveStudents :many
SELECT id, student_code, full_name, date_of_birth, gender, phone, email, address, club_id, group_id, belt_rank_id, joined_at, status, notes, created_at, updated_at, last_modified_at, deleted_at
FROM students
WHERE deleted_at IS NULL
ORDER BY full_name ASC
`

func (q *Queries) ListActiveStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.Query(ctx, listActiveStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.StudentCode,
			&i.FullName,
			&i.DateOfBirth,
			&i.Gender,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.ClubID,
			&i.GroupID,
			&i.BeltRankID,
			&i.JoinedAt,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
