ALTER TABLE club_invites
	ALTER COLUMN invitee_email DROP NOT NULL;

ALTER TABLE club_invites
	ADD COLUMN IF NOT EXISTS max_uses INTEGER NOT NULL DEFAULT 1,
	ADD COLUMN IF NOT EXISTS use_count INTEGER NOT NULL DEFAULT 0,
	ADD COLUMN IF NOT EXISTS last_used_at TIMESTAMPTZ NULL,
	ADD COLUMN IF NOT EXISTS accepted_by_user_id TEXT NULL REFERENCES users(id);
